name: Build and release dorcs 
on:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    name: Build and upload
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'gunnel-linux'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'gunnel-windows'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'gunnel-macos'
            platform:  'darwin/universal'
            os: 'macos-latest'
    runs-on: ${{ matrix.build.os }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        run: |
          version=$(grep -o 'const version = "[^"]*"' main.go | cut -d'"' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.23'
          wails-version: 'v2.9.2'
          node-version: '20.11.1'
